title: KTMS Wiki
description: Wiki page for KTMS
url: "https://catacombnoop.github.io/" # The base hostname & protocol for your site

# Theme settings
remote_theme: mmistakes/minimal-mistakes

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme # add this line to the plugins list if you already have one

# Other custom settings


